<?php

use Illuminate\Database\Seeder;

class CommuneTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('communes')->insert([
            ['id' => 1 ,'name' => 'Arica', 'code_deis' => '15101', 'region_id' => 16],
            ['id' => 2 ,'name' => 'Putre', 'code_deis' => '15201', 'region_id' => 16],
            ['id' => 3 ,'name' => 'General Lagos', 'code_deis' => '15202', 'region_id' => 16],
            ['id' => 4 ,'name' => 'Camarones', 'code_deis' => '15102', 'region_id' => 16]/*,
            ['id' => 5 ,'name' => 'Iquique', 'code_deis' => '1101', 'population' => 223463, 'region_id' => 1],
            ['id' => 6 ,'name' => 'Pica', 'code_deis' => '1405', 'population' => 5958,  'region_id' => 1],
            ['id' => 7 ,'name' => 'Alto Hospicio', 'code_deis' => '1107', 'population' => 129999, 'region_id' => 1],
            ['id' => 8 ,'name' => 'Pozo Almonte', 'code_deis' => '1401','population' => 17395, 'region_id' => 1],
            ['id' => 9 ,'name' => 'Huara', 'code_deis' => '1404', 'population' => 3000, 'region_id' => 1],
            ['id' => 10 ,'name' => 'Camiña', 'code_deis' => '1402', 'population' => 1375, 'region_id' => 1],
            ['id' => 11 ,'name' => 'Colchane', 'code_deis' => '1403', 'population' => 1583, 'region_id' => 1],
            ['id' => 12 ,'name' => 'Antofagasta', 'code_deis' => '2101', 'region_id' => 2],
            ['id' => 13 ,'name' => 'Calama', 'code_deis' => '2201', 'region_id' => 2],
            ['id' => 14 ,'name' => 'Tocopilla', 'code_deis' => '2301', 'region_id' => 2],
            ['id' => 15 ,'name' => 'Taltal', 'code_deis' => '2104', 'region_id' => 2],
            ['id' => 16 ,'name' => 'Mejillones', 'code_deis' => '2102', 'region_id' => 2],
            ['id' => 17 ,'name' => 'Maria Elena', 'code_deis' => '2302', 'region_id' => 2],
            ['id' => 18 ,'name' => 'San Pedro de Atacama', 'code_deis' => '2203', 'region_id' => 2],
            ['id' => 19 ,'name' => 'Sierra Gorda', 'code_deis' => '2103', 'region_id' => 2],
            ['id' => 20 ,'name' => 'Ollagüe', 'code_deis' => '2202', 'region_id' => 2],
            ['id' => 21 ,'name' => 'Copiapó', 'code_deis' => '3101', 'region_id' => 3],
            ['id' => 22 ,'name' => 'Chañaral', 'code_deis' => '3201', 'region_id' => 3],
            ['id' => 23 ,'name' => 'Diego de Almagro', 'code_deis' => '3202', 'region_id' => 3],
            ['id' => 24 ,'name' => 'Vallenar', 'code_deis' => '3301', 'region_id' => 3],
            ['id' => 25 ,'name' => 'Huasco', 'code_deis' => '3304', 'region_id' => 3],
            ['id' => 26 ,'name' => 'Caldera', 'code_deis' => '3102', 'region_id' => 3],
            ['id' => 27 ,'name' => 'Tierra Amarilla', 'code_deis' => '3103', 'region_id' => 3],
            ['id' => 28 ,'name' => 'Freirina', 'code_deis' => '3303', 'region_id' => 3],
            ['id' => 29 ,'name' => 'Alto del Carmen', 'code_deis' => '3302', 'region_id' => 3],
            ['id' => 30 ,'name' => 'La Serena', 'code_deis' => '4101', 'region_id' => 4],
            ['id' => 31 ,'name' => 'Monte Patria', 'code_deis' => '4303', 'region_id' => 4],
            ['id' => 32 ,'name' => 'Coquimbo', 'code_deis' => '4102', 'region_id' => 4],
            ['id' => 33 ,'name' => 'Ovalle', 'code_deis' => '4301', 'region_id' => 4],
            ['id' => 34 ,'name' => 'Illapel', 'code_deis' => '4201', 'region_id' => 4],
            ['id' => 35 ,'name' => 'Salamanca', 'code_deis' => '4204', 'region_id' => 4],
            ['id' => 36 ,'name' => 'Combarbalá', 'code_deis' => '4302', 'region_id' => 4],
            ['id' => 37 ,'name' => 'Andacollo', 'code_deis' => '4103', 'region_id' => 4],
            ['id' => 38 ,'name' => 'Vicuña', 'code_deis' => '4106', 'region_id' => 4],
            ['id' => 39 ,'name' => 'Los Vilos', 'code_deis' => '4203', 'region_id' => 4],
            ['id' => 40 ,'name' => 'Paihuano', 'code_deis' => '4105', 'region_id' => 4],
            ['id' => 41 ,'name' => 'Punitaqui', 'code_deis' => '4304', 'region_id' => 4],
            ['id' => 42 ,'name' => 'Canela', 'code_deis' => '4202', 'region_id' => 4],
            ['id' => 43 ,'name' => 'Río Hurtado', 'code_deis' => '4305', 'region_id' => 4],
            ['id' => 44 ,'name' => 'La Higuera', 'code_deis' => '4104', 'region_id' => 4],
            ['id' => 45 ,'name' => 'Valparaíso', 'code_deis' => '5101', 'region_id' => 5],
            ['id' => 46 ,'name' => 'San Antonio', 'code_deis' => '5601', 'region_id' => 5],
            ['id' => 47 ,'name' => 'Casablanca', 'code_deis' => '5102', 'region_id' => 5],
            ['id' => 48 ,'name' => 'Cartagena', 'code_deis' => '5603', 'region_id' => 5],
            ['id' => 49 ,'name' => 'Algarrobo', 'code_deis' => '5602', 'region_id' => 5],
            ['id' => 50 ,'name' => 'El Quisco', 'code_deis' => '5604', 'region_id' => 5],
            ['id' => 51 ,'name' => 'Santo Domingo', 'code_deis' => '5606', 'region_id' => 5],
            ['id' => 52 ,'name' => 'El Tabo', 'code_deis' => '5605', 'region_id' => 5],
            ['id' => 53 ,'name' => 'Juan Fernández', 'code_deis' => '5104', 'region_id' => 5],
            ['id' => 54 ,'name' => 'Viña del Mar', 'code_deis' => '5109', 'region_id' => 5],
            ['id' => 55 ,'name' => 'Quillota', 'code_deis' => '5501', 'region_id' => 5],
            ['id' => 56 ,'name' => 'Quilpue', 'code_deis' => '5801', 'region_id' => 5],
            ['id' => 57 ,'name' => 'Calera', 'code_deis' => '5502', 'region_id' => 5],
            ['id' => 58 ,'name' => 'Limache', 'code_deis' => '5802', 'region_id' => 5],
            ['id' => 59 ,'name' => 'La Ligua', 'code_deis' => '5401', 'region_id' => 5],
            ['id' => 61 ,'name' => 'Cabildo', 'code_deis' => '5402', 'region_id' => 5],
            ['id' => 62 ,'name' => 'Petorca', 'code_deis' => '5404', 'region_id' => 5],
            ['id' => 63 ,'name' => 'Quintero', 'code_deis' => '5107', 'region_id' => 5],
            ['id' => 64 ,'name' => 'Villa Alemana', 'code_deis' => '5804', 'region_id' => 5],
            ['id' => 65 ,'name' => 'Con Con', 'code_deis' => '5103', 'region_id' => 5],
            ['id' => 66 ,'name' => 'La Cruz', 'code_deis' => '5504', 'region_id' => 5],
            ['id' => 67 ,'name' => 'Puchuncaví', 'code_deis' => '5105', 'region_id' => 5],
            ['id' => 68 ,'name' => 'Olmué', 'code_deis' => '5803', 'region_id' => 5],
            ['id' => 69 ,'name' => 'Hijuelas', 'code_deis' => '5503', 'region_id' => 5],
            ['id' => 71 ,'name' => 'Nogales', 'code_deis' => '5506', 'region_id' => 5],
            ['id' => 72 ,'name' => 'Papudo', 'code_deis' => '5403', 'region_id' => 5],
            ['id' => 73 ,'name' => 'Zapallar', 'code_deis' => '5405', 'region_id' => 5],
            ['id' => 74 ,'name' => 'San Felipe', 'code_deis' => '5701', 'region_id' => 5],
            ['id' => 75 ,'name' => 'Los Andes', 'code_deis' => '5301', 'region_id' => 5],
            ['id' => 76 ,'name' => 'Llaillay', 'code_deis' => '5703', 'region_id' => 5],
            ['id' => 77 ,'name' => 'Putaendo', 'code_deis' => '5705', 'region_id' => 5],
            ['id' => 78 ,'name' => 'Rinconada', 'code_deis' => '5303', 'region_id' => 5],
            ['id' => 79 ,'name' => 'San Esteban', 'code_deis' => '5304', 'region_id' => 5],
            ['id' => 80 ,'name' => 'Catemu', 'code_deis' => '5702', 'region_id' => 5],
            ['id' => 81 ,'name' => 'Calle Larga', 'code_deis' => '5302', 'region_id' => 5],
            ['id' => 82 ,'name' => 'Santa Maria', 'code_deis' => '5706', 'region_id' => 5],
            ['id' => 83 ,'name' => 'Panquehue', 'code_deis' => '5704', 'region_id' => 5],
            ['id' => 84 ,'name' => 'Independencia', 'code_deis' => '13108', 'region_id' => 6],
            ['id' => 85 ,'name' => 'Tiltil', 'code_deis' => '13303', 'region_id' => 6],
            ['id' => 86 ,'name' => 'Recoleta', 'code_deis' => '13127', 'region_id' => 6],
            ['id' => 87 ,'name' => 'Huechuraba', 'code_deis' => '13107', 'region_id' => 6],
            ['id' => 88 ,'name' => 'Quilicura', 'code_deis' => '13125', 'region_id' => 6],
            ['id' => 89 ,'name' => 'Colina', 'code_deis' => '13301', 'region_id' => 6],
            ['id' => 90 ,'name' => 'Conchalí', 'code_deis' => '13104', 'region_id' => 6],
            ['id' => 91 ,'name' => 'Lampa', 'code_deis' => '13302', 'region_id' => 6],
            ['id' => 92 ,'name' => 'Santiago', 'code_deis' => '13101', 'region_id' => 6],
            ['id' => 93 ,'name' => 'Curacaví', 'code_deis' => '13503', 'region_id' => 6],
            ['id' => 94 ,'name' => 'Quinta Normal', 'code_deis' => '13126', 'region_id' => 6],
            ['id' => 95 ,'name' => 'Talagante', 'code_deis' => '13601', 'region_id' => 6],
            ['id' => 96 ,'name' => 'Peñaflor', 'code_deis' => '13605', 'region_id' => 6],
            ['id' => 97 ,'name' => 'Melipilla', 'code_deis' => '13501', 'region_id' => 6],
            ['id' => 98 ,'name' => 'Pudahuel', 'code_deis' => '13124', 'region_id' => 6],
            ['id' => 99 ,'name' => 'Lo Prado', 'code_deis' => '13117', 'region_id' => 6],
            ['id' => 100 ,'name' => 'Cerro Navia', 'code_deis' => '13103', 'region_id' => 6],
            ['id' => 101 ,'name' => 'Renca', 'code_deis' => '13128', 'region_id' => 6],
            ['id' => 102 ,'name' => 'Padre Hurtado', 'code_deis' => '13604', 'region_id' => 6],
            ['id' => 103 ,'name' => 'El Monte', 'code_deis' => '13602', 'region_id' => 6],
            ['id' => 104 ,'name' => 'Isla de Maipo', 'code_deis' => '13603', 'region_id' => 6],
            ['id' => 105 ,'name' => 'Maria Pinto', 'code_deis' => '13504', 'region_id' => 6],
            ['id' => 106 ,'name' => 'San Pedro', 'code_deis' => '13505', 'region_id' => 6],
            ['id' => 107 ,'name' => 'Alhué', 'code_deis' => '13502', 'region_id' => 6],
            ['id' => 108 ,'name' => 'Maipú', 'code_deis' => '13119', 'region_id' => 6],
            ['id' => 109 ,'name' => 'Estación Central', 'code_deis' => '13106', 'region_id' => 6],
            ['id' => 110 ,'name' => 'Cerrillos', 'code_deis' => '13102', 'region_id' => 6],
            ['id' => 111 ,'name' => 'Pedro Aguirre Cerda', 'code_deis' => '13121', 'region_id' => 6],
            ['id' => 112 ,'name' => 'Providencia', 'code_deis' => '13123', 'region_id' => 6],
            ['id' => 113 ,'name' => 'Peñalolén', 'code_deis' => '13122', 'region_id' => 6],
            ['id' => 114 ,'name' => 'Isla de Pascua', 'code_deis' => '5201', 'region_id' => 5],
            ['id' => 115 ,'name' => 'Vitacura', 'code_deis' => '13132', 'region_id' => 6],
            ['id' => 116 ,'name' => 'Las Condes', 'code_deis' => '13114', 'region_id' => 6],
            ['id' => 117 ,'name' => 'Macul', 'code_deis' => '13118', 'region_id' => 6],
            ['id' => 118 ,'name' => 'Ñuñoa', 'code_deis' => '13120', 'region_id' => 6],
            ['id' => 119 ,'name' => 'La Reina', 'code_deis' => '13113', 'region_id' => 6],
            ['id' => 120 ,'name' => 'Lo Barnechea', 'code_deis' => '13115', 'region_id' => 6],
            ['id' => 121 ,'name' => 'San Miguel', 'code_deis' => '13130', 'region_id' => 6],
            ['id' => 122 ,'name' => 'Buin', 'code_deis' => '13402', 'region_id' => 6],
            ['id' => 123 ,'name' => 'Puente Alto', 'code_deis' => '13201', 'region_id' => 6],
            ['id' => 124 ,'name' => 'San Bernardo', 'code_deis' => '13401', 'region_id' => 6],
            ['id' => 125 ,'name' => 'Lo Espejo', 'code_deis' => '13116', 'region_id' => 6],
            ['id' => 126 ,'name' => 'San Joaquín', 'code_deis' => '13129', 'region_id' => 6],
            ['id' => 127 ,'name' => 'Paine', 'code_deis' => '13404', 'region_id' => 6],
            ['id' => 128 ,'name' => 'El Bosque', 'code_deis' => '13105', 'region_id' => 6],
            ['id' => 129 ,'name' => 'La Cisterna', 'code_deis' => '13109', 'region_id' => 6],
            ['id' => 130 ,'name' => 'La Granja', 'code_deis' => '13111', 'region_id' => 6],
            ['id' => 131 ,'name' => 'Calera de Tango', 'code_deis' => '13403', 'region_id' => 6],
            ['id' => 132 ,'name' => 'San José de Maipo', 'code_deis' => '13203', 'region_id' => 6],
            ['id' => 133 ,'name' => 'San Ramón', 'code_deis' => '13131', 'region_id' => 6],
            ['id' => 134 ,'name' => 'La Florida', 'code_deis' => '13110', 'region_id' => 6],
            ['id' => 135 ,'name' => 'La Pintana', 'code_deis' => '13112', 'region_id' => 6],
            ['id' => 136 ,'name' => 'Pirque', 'code_deis' => '13202', 'region_id' => 6],
            ['id' => 137 ,'name' => 'Rancagua', 'code_deis' => '6101', 'region_id' => 7],
            ['id' => 138 ,'name' => 'Graneros', 'code_deis' => '6106', 'region_id' => 7],
            ['id' => 139 ,'name' => 'Coinco', 'code_deis' => '6103', 'region_id' => 7],
            ['id' => 140 ,'name' => 'Peumo', 'code_deis' => '6112', 'region_id' => 7],
            ['id' => 141 ,'name' => 'Rengo', 'code_deis' => '6115', 'region_id' => 7],
            ['id' => 142 ,'name' => 'San Vicente', 'code_deis' => '6117', 'region_id' => 7],
            ['id' => 143 ,'name' => 'Pichidegua', 'code_deis' => '6113', 'region_id' => 7],
            ['id' => 144 ,'name' => 'San Fernando', 'code_deis' => '6301', 'region_id' => 7],
            ['id' => 145 ,'name' => 'Chimbarongo', 'code_deis' => '6303', 'region_id' => 7],
            ['id' => 146 ,'name' => 'Nancagua', 'code_deis' => '6305', 'region_id' => 7],
            ['id' => 147 ,'name' => 'Santa Cruz', 'code_deis' => '6310', 'region_id' => 7],
            ['id' => 148 ,'name' => 'Marchihue', 'code_deis' => '6204', 'region_id' => 7],
            ['id' => 149 ,'name' => 'Pichilemu', 'code_deis' => '6201', 'region_id' => 7],
            ['id' => 150 ,'name' => 'Lolol', 'code_deis' => '6304', 'region_id' => 7],
            ['id' => 151 ,'name' => 'Litueche', 'code_deis' => '6203', 'region_id' => 7],
            ['id' => 152 ,'name' => 'Machalí', 'code_deis' => '6108', 'region_id' => 7],
            ['id' => 153 ,'name' => 'Mostazal', 'code_deis' => '6110', 'region_id' => 7],
            ['id' => 154 ,'name' => 'Codegua', 'code_deis' => '6102', 'region_id' => 7],
            ['id' => 155 ,'name' => 'Doñihue', 'code_deis' => '6105', 'region_id' => 7],
            ['id' => 156 ,'name' => 'Coltauco', 'code_deis' => '6104', 'region_id' => 7],
            ['id' => 157 ,'name' => 'Requínoa', 'code_deis' => '6116', 'region_id' => 7],
            ['id' => 158 ,'name' => 'Las Cabras', 'code_deis' => '6107', 'region_id' => 7],
            ['id' => 159 ,'name' => 'Quinta de Tilcoco', 'code_deis' => '6114', 'region_id' => 7],
            ['id' => 160 ,'name' => 'Peralillo', 'code_deis' => '6307', 'region_id' => 7],
            ['id' => 161 ,'name' => 'La Estrella', 'code_deis' => '6202', 'region_id' => 7],
            ['id' => 162 ,'name' => 'Chepica', 'code_deis' => '6302', 'region_id' => 7],
            ['id' => 163 ,'name' => 'Paredones', 'code_deis' => '6206', 'region_id' => 7],
            ['id' => 164 ,'name' => 'Placilla', 'code_deis' => '6308', 'region_id' => 7],
            ['id' => 165 ,'name' => 'Navidad', 'code_deis' => '6205', 'region_id' => 7],
            ['id' => 166 ,'name' => 'Malloa', 'code_deis' => '6109', 'region_id' => 7],
            ['id' => 167 ,'name' => 'Olivar', 'code_deis' => '6111', 'region_id' => 7],
            ['id' => 168 ,'name' => 'Palmilla', 'code_deis' => '6306', 'region_id' => 7],
            ['id' => 169 ,'name' => 'Pumanque', 'code_deis' => '6309', 'region_id' => 7],
            ['id' => 170 ,'name' => 'Talca', 'code_deis' => '7101', 'region_id' => 8],
            ['id' => 171 ,'name' => 'Curicó', 'code_deis' => '7301', 'region_id' => 8],
            ['id' => 172 ,'name' => 'Teno', 'code_deis' => '7308', 'region_id' => 8],
            ['id' => 173 ,'name' => 'Molina', 'code_deis' => '7304', 'region_id' => 8],
            ['id' => 174 ,'name' => 'Hualañé', 'code_deis' => '7302', 'region_id' => 8],
            ['id' => 175 ,'name' => 'Licantén', 'code_deis' => '7303', 'region_id' => 8],
            ['id' => 176 ,'name' => 'Curepto', 'code_deis' => '7103', 'region_id' => 8],
            ['id' => 177 ,'name' => 'Constitución', 'code_deis' => '7102', 'region_id' => 8],
            ['id' => 178 ,'name' => 'Linares', 'code_deis' => '7401', 'region_id' => 8],
            ['id' => 179 ,'name' => 'San Javier', 'code_deis' => '7406', 'region_id' => 8],
            ['id' => 180 ,'name' => 'Parral', 'code_deis' => '7404', 'region_id' => 8],
            ['id' => 181 ,'name' => 'Cauquenes', 'code_deis' => '7201', 'region_id' => 8],
            ['id' => 182 ,'name' => 'Chanco', 'code_deis' => '7202', 'region_id' => 8],
            ['id' => 183 ,'name' => 'Villa Alegre', 'code_deis' => '7407', 'region_id' => 8],
            ['id' => 184 ,'name' => 'Pencahue', 'code_deis' => '7107', 'region_id' => 8],
            ['id' => 185 ,'name' => 'San Clemente', 'code_deis' => '7109', 'region_id' => 8],
            ['id' => 186 ,'name' => 'Maule', 'code_deis' => '7105', 'region_id' => 8],
            ['id' => 187 ,'name' => 'Pelarco', 'code_deis' => '7106', 'region_id' => 8],
            ['id' => 188 ,'name' => 'Río Claro', 'code_deis' => '7108', 'region_id' => 8],
            ['id' => 189 ,'name' => 'Colbún', 'code_deis' => '7402', 'region_id' => 8],
            ['id' => 190 ,'name' => 'Yerbas Buenas', 'code_deis' => '7408', 'region_id' => 8],
            ['id' => 191 ,'name' => 'Longaví', 'code_deis' => '7403', 'region_id' => 8],
            ['id' => 192 ,'name' => 'Retiro', 'code_deis' => '7405', 'region_id' => 8],
            ['id' => 193 ,'name' => 'Pelluhue', 'code_deis' => '7203', 'region_id' => 8],
            ['id' => 194 ,'name' => 'San Rafael', 'code_deis' => '7110', 'region_id' => 8],
            ['id' => 195 ,'name' => 'Sagrada Familia', 'code_deis' => '7307', 'region_id' => 8],
            ['id' => 196 ,'name' => 'Vichuquén', 'code_deis' => '7309', 'region_id' => 8],
            ['id' => 197 ,'name' => 'Romeral', 'code_deis' => '7306', 'region_id' => 8],
            ['id' => 198 ,'name' => 'Rauco', 'code_deis' => '7305', 'region_id' => 8],
            ['id' => 199 ,'name' => 'Empedrado', 'code_deis' => '7104', 'region_id' => 8],
            ['id' => 200 ,'name' => 'Chillán', 'code_deis' => '16101', 'region_id' => 9],
            ['id' => 201 ,'name' => 'San Carlos', 'code_deis' => '16301', 'region_id' => 9],
            ['id' => 202 ,'name' => 'Bulnes', 'code_deis' => '16102', 'region_id' => 9],
            ['id' => 203 ,'name' => 'Yungay', 'code_deis' => '16109', 'region_id' => 9],
            ['id' => 204 ,'name' => 'Quirihue', 'code_deis' => '16201', 'region_id' => 9],
            ['id' => 205 ,'name' => 'El Carmen', 'code_deis' => '16104', 'region_id' => 9],
            ['id' => 206 ,'name' => 'Coelemu', 'code_deis' => '16203', 'region_id' => 9],
            ['id' => 207 ,'name' => 'Portezuelo', 'code_deis' => '16205', 'region_id' => 9],
            ['id' => 208 ,'name' => 'Quillón', 'code_deis' => '16107', 'region_id' => 9],
            ['id' => 209 ,'name' => 'Cobquecura', 'code_deis' => '16202', 'region_id' => 9],
            ['id' => 210 ,'name' => 'San Ignacio', 'code_deis' => '16108', 'region_id' => 9],
            ['id' => 211 ,'name' => 'San Fabián', 'code_deis' => '16304', 'region_id' => 9],
            ['id' => 212 ,'name' => 'Pemuco', 'code_deis' => '16105', 'region_id' => 9],
            ['id' => 213 ,'name' => 'San Nicolás', 'code_deis' => '16305', 'region_id' => 9],
            ['id' => 214 ,'name' => 'Ñiquén', 'code_deis' => '16303', 'region_id' => 9],
            ['id' => 215 ,'name' => 'Ninhue', 'code_deis' => '16204', 'region_id' => 9],
            ['id' => 216 ,'name' => 'Ránquil', 'code_deis' => '16206', 'region_id' => 9],
            ['id' => 217 ,'name' => 'Pinto', 'code_deis' => '16106', 'region_id' => 9],
            ['id' => 218 ,'name' => 'Coihueco', 'code_deis' => '16302', 'region_id' => 9],
            ['id' => 219 ,'name' => 'Treguaco', 'code_deis' => '16207', 'region_id' => 9],
            ['id' => 220 ,'name' => 'Chillán Viejo', 'code_deis' => '16103', 'region_id' => 9],
            ['id' => 221 ,'name' => 'Concepción', 'code_deis' => '8101', 'region_id' => 10],
            ['id' => 222 ,'name' => 'Coronel', 'code_deis' => '8102', 'region_id' => 10],
            ['id' => 223 ,'name' => 'Lota', 'code_deis' => '8106', 'region_id' => 10],
            ['id' => 224 ,'name' => 'Santa Juana', 'code_deis' => '8109', 'region_id' => 10],
            ['id' => 225 ,'name' => 'Florida', 'code_deis' => '8104', 'region_id' => 10],
            ['id' => 226 ,'name' => 'Talcahuano', 'code_deis' => '8110', 'region_id' => 10],
            ['id' => 227 ,'name' => 'Hualpén', 'code_deis' => '8112', 'region_id' => 10],
            ['id' => 228 ,'name' => 'San Pedro de la Paz', 'code_deis' => '8108', 'region_id' => 10],
            ['id' => 229 ,'name' => 'Chiguayante', 'code_deis' => '8103', 'region_id' => 10],
            ['id' => 230 ,'name' => 'Hualqui', 'code_deis' => '8105', 'region_id' => 10],
            ['id' => 231 ,'name' => 'Tome', 'code_deis' => '8111', 'region_id' => 10],
            ['id' => 232 ,'name' => 'Penco', 'code_deis' => '8107', 'region_id' => 10],
            ['id' => 233 ,'name' => 'Los Ángeles', 'code_deis' => '8301', 'region_id' => 10],
            ['id' => 234 ,'name' => 'Tucapel', 'code_deis' => '8312', 'region_id' => 10],
            ['id' => 235 ,'name' => 'Santa Bárbara', 'code_deis' => '8311', 'region_id' => 10],
            ['id' => 236 ,'name' => 'Yumbel', 'code_deis' => '8313', 'region_id' => 10],
            ['id' => 237 ,'name' => 'Mulchén', 'code_deis' => '8305', 'region_id' => 10],
            ['id' => 238 ,'name' => 'Nacimiento', 'code_deis' => '8306', 'region_id' => 10],
            ['id' => 239 ,'name' => 'Laja', 'code_deis' => '8304', 'region_id' => 10],
            ['id' => 240 ,'name' => 'Cabrero', 'code_deis' => '8303', 'region_id' => 10],
            ['id' => 241 ,'name' => 'Antuco', 'code_deis' => '8302', 'region_id' => 10],
            ['id' => 242 ,'name' => 'Quilleco', 'code_deis' => '8309', 'region_id' => 10],
            ['id' => 243 ,'name' => 'Negrete', 'code_deis' => '8307', 'region_id' => 10],
            ['id' => 244 ,'name' => 'San Rosendo', 'code_deis' => '8310', 'region_id' => 10],
            ['id' => 245 ,'name' => 'Alto Biobío', 'code_deis' => '8314', 'region_id' => 10],
            ['id' => 246 ,'name' => 'Quilaco', 'code_deis' => '8308', 'region_id' => 10],
            ['id' => 247 ,'name' => 'Temuco', 'code_deis' => '9101', 'region_id' => 11],
            ['id' => 248 ,'name' => 'Lautaro', 'code_deis' => '9108', 'region_id' => 11],
            ['id' => 249 ,'name' => 'Galvarino', 'code_deis' => '9106', 'region_id' => 11],
            ['id' => 250 ,'name' => 'Vilcún', 'code_deis' => '9119', 'region_id' => 11],
            ['id' => 251 ,'name' => 'Cunco', 'code_deis' => '9103', 'region_id' => 11],
            ['id' => 252 ,'name' => 'Nueva Imperial', 'code_deis' => '9111', 'region_id' => 11],
            ['id' => 253 ,'name' => 'Carahue', 'code_deis' => '9102', 'region_id' => 11],
            ['id' => 254 ,'name' => 'Saavedra', 'code_deis' => '9116', 'region_id' => 11],
            ['id' => 255 ,'name' => 'Pitrufquén', 'code_deis' => '9114', 'region_id' => 11],
            ['id' => 256 ,'name' => 'Toltén', 'code_deis' => '9118', 'region_id' => 11],
            ['id' => 257 ,'name' => 'Gorbea', 'code_deis' => '9107', 'region_id' => 11],
            ['id' => 258 ,'name' => 'Loncoche', 'code_deis' => '9109', 'region_id' => 11],
            ['id' => 259 ,'name' => 'Villarrica', 'code_deis' => '9120', 'region_id' => 11],
            ['id' => 260 ,'name' => 'Pucón', 'code_deis' => '9115', 'region_id' => 11],
            ['id' => 261 ,'name' => 'Padre Las Casas', 'code_deis' => '9112', 'region_id' => 11],
            ['id' => 262 ,'name' => 'Freire', 'code_deis' => '9105', 'region_id' => 11],
            ['id' => 263 ,'name' => 'Melipeuco', 'code_deis' => '9110', 'region_id' => 11],
            ['id' => 264 ,'name' => 'Teodoro Schmidt', 'code_deis' => '9117', 'region_id' => 11],
            ['id' => 265 ,'name' => 'Curarrehue', 'code_deis' => '9104', 'region_id' => 11],
            ['id' => 266 ,'name' => 'Perquenco', 'code_deis' => '9113', 'region_id' => 11],
            ['id' => 267 ,'name' => 'Cholchol', 'code_deis' => '9121', 'region_id' => 11],
            ['id' => 268 ,'name' => 'Valdivia', 'code_deis' => '14101', 'region_id' => 12],
            ['id' => 269 ,'name' => 'Corral', 'code_deis' => '14102', 'region_id' => 12],
            ['id' => 270 ,'name' => 'Los Lagos', 'code_deis' => '14104', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Lanco', 'code_deis' => '14103', 'region_id' => 12],
            ['id' => 11 ,'name' => 'La Unión', 'code_deis' => '14201', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Río Bueno', 'code_deis' => '14204', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Paillaco', 'code_deis' => '14107', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Mariquina', 'code_deis' => '14106', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Panguipulli', 'code_deis' => '14108', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Futrono', 'code_deis' => '14202', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Lago Ranco', 'code_deis' => '14203', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Máfil', 'code_deis' => '14105', 'region_id' => 12],
            ['id' => 11 ,'name' => 'Osorno', 'code_deis' => '10301', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Purranque', 'code_deis' => '10303', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Río Negro', 'code_deis' => '10305', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Puerto Octay', 'code_deis' => '10302', 'region_id' => 13],
            ['id' => 11 ,'name' => 'San Juan de la Costa', 'code_deis' => '10306', 'region_id' => 13],
            ['id' => 11 ,'name' => 'San Pablo', 'code_deis' => '10307', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Puyehue', 'code_deis' => '10304', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Puerto Montt', 'code_deis' => '10101', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Llanquihue', 'code_deis' => '10107', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Frutillar', 'code_deis' => '10105', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Fresia', 'code_deis' => '10104', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Maullín', 'code_deis' => '10108', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Calbuco', 'code_deis' => '10102', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Palena', 'code_deis' => '10404', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Futaleufú', 'code_deis' => '10402', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Puerto Varas', 'code_deis' => '10109', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Los Muermos', 'code_deis' => '10106', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Hualaihué', 'code_deis' => '10403', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Cochamó', 'code_deis' => '10103', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Chaitén', 'code_deis' => '10401', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Coyhaique', 'code_deis' => '11101', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Aisén', 'code_deis' => '11201', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Chile Chico', 'code_deis' => '11401', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Cochrane', 'code_deis' => '11301', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Cisnes', 'code_deis' => '11202', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Guaitecas', 'code_deis' => '11203', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Lago Verde', 'code_deis' => '11102', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Río Ibáñez', 'code_deis' => '11402', 'region_id' => 14],
            ['id' => 11 ,'name' => 'OHiggins', 'code_deis' => '11302', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Tortel', 'code_deis' => '11303', 'region_id' => 14],
            ['id' => 11 ,'name' => 'Punta Arenas', 'code_deis' => '12101', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Natales', 'code_deis' => '12401', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Porvenir', 'code_deis' => '12301', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Cabo de Hornos', 'code_deis' => '12201', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Primavera', 'code_deis' => '12302', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Torres del Paine', 'code_deis' => '12402', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Río Verde', 'code_deis' => '12103', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Laguna Blanca', 'code_deis' => '12102', 'region_id' => 15],
            ['id' => 11 ,'name' => 'San Gregorio', 'code_deis' => '12104', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Timaukel', 'code_deis' => '12303', 'region_id' => 15],
            ['id' => 11 ,'name' => 'Lebu', 'code_deis' => '8201', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Curanilahue', 'code_deis' => '8205', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Cañete', 'code_deis' => '8203', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Contulmo', 'code_deis' => '8204', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Arauco', 'code_deis' => '8202', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Tirúa', 'code_deis' => '8207', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Los Álamos', 'code_deis' => '8206', 'region_id' => 10],
            ['id' => 11 ,'name' => 'Angol', 'code_deis' => '9201', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Purén', 'code_deis' => '9208', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Los Sauces', 'code_deis' => '9206', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Collipulli', 'code_deis' => '9202', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Traiguén', 'code_deis' => '9210', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Lumaco', 'code_deis' => '9207', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Victoria', 'code_deis' => '9211', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Curacautín', 'code_deis' => '9203', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Lonquimay', 'code_deis' => '9205', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Renaico', 'code_deis' => '9209', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Ercilla', 'code_deis' => '9204', 'region_id' => 11],
            ['id' => 11 ,'name' => 'Castro', 'code_deis' => '10201', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Ancud', 'code_deis' => '10202', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Quinchao', 'code_deis' => '10210', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Quellón', 'code_deis' => '10208', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Queilén', 'code_deis' => '10207', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Quemchi', 'code_deis' => '10209', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Chonchi', 'code_deis' => '10203', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Dalcahue', 'code_deis' => '10205', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Puqueldón', 'code_deis' => '10206', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Curaco de Vélez', 'code_deis' => '10204', 'region_id' => 13],
            ['id' => 11 ,'name' => 'Coñaripe', 'code_deis' => '14108', 'region_id' => 12]*/
        ]);
        
    }
}
